### ISSUE TITLE
Show arbitrary data received via UART

### ISSUE THREAD

**Issue by jetdream** [cocus/vc288-alt-fw#2]
Feature request
Use indicators to show arbitrary data received via UART

**Comment by cocus** [comment]
This is more-or-less the same situation as in #1. However, you could emulate a software UART on the pins that both ADC were used. This would require to desolder some components, and of course, loosing the ability to measure anything locally. It will behave as a dumb display only.

**Comment by jetdream** [comment]
It does not seem a feasible option.
