### ISSUE TITLE
incorrect display of characters

### ISSUE THREAD

**Issue by ksv-success** [cocus/vc288-alt-fw#5]
Displays the letter A upside down and commas for 4 divisions 3 upper and one lower 2 more not lit at all... please help me. How to fix the normal display? to show everywhere 0 and commas only where necessary.

**Comment by cocus** [comment]
Can you attach a picture? I'm not sure that the code is working fine in your case

**Comment by ksv-success** [comment]
https://drive.google.com/file/d/1BpL0PhPKnyi3P_CUpdUIE2z21mtPlmv9/view
may need an old version of IAR

**Comment by cocus** [comment]
I need access to the specified link.

Oh, I forgot to also mention that you should comment out this line:
`#define SWIM_DEBUG_ENABLED`
Otherwise one of the segments will not be used (so you can debug the board).

**Comment by ksv-success** [comment]
now the top segment works but it's not zeros) 8.8.8. shows please forgive me, I just don’t understand much about programming, don’t tell me how to fix it, that would work fine

**Comment by cocus** [comment]
Ok, let's test if you can get some life out of it. Hardcode the values for the top and bottom rows on lines 97 and 103 of main.c; set something like 1234 for line 97 and 5678 for line 103.

**Comment by ksv-success** [comment]
if correctly understood such a record should be? ![image](https://user-images.githubusercontent.com/59658638/71999935-52243380-3253-11ea-9d11-afdc4f24fc4f.png)

**Comment by cocus** [comment]
Sorry, no. Use 1234 and 5678 instead of `value`. Leave the 3 and 0 for the other argument. And that should print "1234" on one row, and then 5678 on the other row.

**Comment by ksv-success** [comment]
![image](https://user-images.githubusercontent.com/59658638/72000468-6f0d3680-3254-11ea-8af5-114afef1a451.png)
still shows 8.8.8 and 8.

**Comment by cocus** [comment]
Yes, you can't debug if you disable the flag I mentioned before. Because of the design of this meter, the debug interface is also used for the display!

Okay, please try flashing it, disconnecting the debugger, and power cycle it?

And also, can you verify that it's the same MCU, same PCB and check the connections between MCU and display? A picture of it (including the PCB) would be greatly appreciated!

**Comment by ksv-success** [comment]
well, thanks, as I understand it should work apparently with my board something I will investigate the PCB something is trying to show some numbers but poorly distinguishable because it burns too bright 
my previous STM8 burned out, replaced, I’m tormenting it, and there were displays with a common cathode, I bought a common anode, I put such ones, so it doesn’t work

**Comment by ksv-success** [comment]
I'm from Russia using Google translator) thanks for your time)

**Comment by cocus** [comment]
Oh I see; the schematic that I've used match my PCB (have a look here: https://github.com/Upcycle-Electronics/DSN-VC288/blob/master/PDF's/V2.0%20DSN-VC288.pdf).
No worries about the language! If something is burning the display (or the MCU), please check the voltage rails first. Also, my board had a nuvoton MCU originally and I changed it to an STM8S003F, but it's the exact same PCB for the one showed in that PCB (amazing how they've managed to clone even the pinouts from nuvoton to stm).

**Comment by ksv-success** [comment]
the board is identical to yours I also have NUVOTON I replaced it with the STM8S103F

**Comment by ksv-success** [comment]
Now I understand I need NUVOTON

**Comment by cocus** [comment]
Right, but this firmware is aimed for the STM8S003F. I don't have an 8S103F to try. Can you update the project type to 103F and try again? I'm not sure if there are more stuff to be changed.
You should not use the nuvoton!

**Comment by ksv-success** [comment]
ok try to upgrade to STM8S103

**Comment by ksv-success** [comment]
updated the same as far as I understand STM8S003 and STM8S103 are the same

**Comment by ksv-success** [comment]
А оригинальной прошивки у вас не осталось случайно? или она не подойдет на STM8

**Comment by cocus** [comment]
I couldn't read the original firmware since mine had the Nuvoton chip, so I don't have access to original STM8 firmwares. It would be interesting to have them. In any case, you can go back to the nuvoton if you really need the meter.

Also, I'm not sure if the S003 and S103 are "exactly" the same. Some initialization must be wrong, otherwise you'll get a proper display out. I would have to check if the MCU has some additional configuration for the GPIOs. If you can, you could give that a look. I would accept any feedback!

**Comment by ksv-success** [comment]
нужен да и STM8 я через ардуино Ide выводил числа от 0 до 9 и запятую на большее не хватило моих знаний в программировании

**Comment by ksv-success** [comment]
возможно из за операционного усилителя такие глюки? может он тоже сгорел?

**Comment by cocus** [comment]
I don't think it's the opamp burned. I think there's an issue with the GPIO mapping or the GPIOs are not configured as they should. Probably the STM8S103 has more alternate functions on the pins and you need to turn them off to use them as a simple I/O port.

**Comment by ksv-success** [comment]
как отключить эти GPIO?

**Comment by ksv-success** [comment]
![image](https://user-images.githubusercontent.com/59658638/72006178-2196c680-3260-11ea-947a-9d7bed580b84.png)
Отключать я так понял нужно здесь

**Comment by cocus** [comment]
No, actually you don't want to disable the GPIOs, but rather "other alternate functions" that you don't need for GPIO. I'm assuming that would be.

**Comment by ksv-success** [comment]
может все дело в дисплее заменить на дисплей с общим катодом или это все равно

**Comment by cocus** [comment]
Well, the original diagram called for a common anode display (i.e. 3 anodes for each column and 8 cathodes for the segments). If you use a common cathode, then some small changes need to be addressed on gpio.c; probably like adding: 
`data ^= 0xFF;` at line 107 of gpio.c
and 
`digit ^= 0xFF;` at line 124 of gpio.c

that "might work" for a common cathode. Give it a try.

**Comment by ksv-success** [comment]
сейчас установлены 2 с общим анодом раньше стояли 2 с общим катодом

**Comment by ksv-success** [comment]
/**
     * First row of LEDs (common anodes)
     * (by default, every LED digit is off)
     */
    PD_DDR_DDR5 = 1; /* PD5 = out */
    PD_CR1_C15 = 0;  /* push pull */
    PD_CR2_C25 = 0;  /* speed 2MHz*/

    PD_DDR_DDR4 = 1; /* PD4 = out */
    PD_CR1_C14 = 0;  /* push pull */
    PD_CR2_C24 = 0;  /* speed 2MHz*/

    /**
     * Second row of LEDs (common anodes)
     * (by default, every LED digit is off)
     */
    PB_DDR_DDR4 = 1; /* PB4 = out */
    PB_CR1_C14 = 0;  /* push pull */
    PB_CR2_C24 = 1;  /* speed 2MHz*/

    PA_DDR_DDR1 = 1; /* PA1 = out */
    PA_CR1_C11 = 0;  /* push pull */
    PA_CR2_C21 = 1;  /* speed 2MHz*/

    PB_DDR_DDR5 = 1; /* PB5 = out */
    PB_CR1_C15 = 0;  /* push pull */
    PB_CR2_C25 = 1;  /* speed 2MHz*/
}

похоже нашел здесь чтото

**Comment by ksv-success** [comment]
сейчас центральная цифра моргает с таким кодом то есть 8 посередине верхнего ряда моргает

**Comment by cocus** [comment]
Yes, don't mind the comments; the code changes I've addressed should make it work with a common cathode.

**Comment by ksv-success** [comment]
Спасибо вам вообщем буду разбираться с GPIO если получится напишу здесь

**Comment by cocus** [comment]
Thank you! Sorry for the lack of support for these different combinations. That's one of the things that are missing on this codebase.

**Comment by ksv-success** [comment]
Получилось сделать 000 и 0 на индикаторах но все равно счётчик не работает

**Comment by ksv-success** [comment]
![IMG_20200109_061102_HDR](https://user-images.githubusercontent.com/59658638/72034961-8fb2ac00-32a7-11ea-9dea-331e168ed0dc.jpg)

**Comment by ksv-success** [comment]
на arduino ide пробовал запустить оба дисплея картина такая же видимо плохо пропаян дисплей либо брак буду проверять 
таким кодом запускал 
int anodPins[3] = { PD4, PD6, PD5 };
int anodPins2[3] = { PB5, PA1, PB4 };
int segmentsPins[8] = {  PD1, PC4, PC7, PC6, PC3, PA3, PA2, PC5  }; //{A, B, C, D, E, F, G, DP}
void setup() {
  // Все выходы программируем как OUTPUT
  for (int i = 0; i < 3; i++) {
    pinMode(anodPins[i], OUTPUT);
    pinMode(anodPins2[i], OUTPUT);
  }
  for (int i = 0; i < 8; i++) {
    pinMode(segmentsPins[i], OUTPUT);
  }
}

//{A, B, C, D, E, F, G, DP} - распиновка сегментов
int seg[10][8] = {
  {0, 0, 0, 0, 0, 0, 1, 1}, // 0
  {1, 1, 1, 1, 0, 0, 1, 1}, // 1
  {0, 1, 0, 0, 1, 0, 0, 1}, // 2
  {0, 1, 1, 0, 0, 0, 0, 1}, // 3
  {1, 0, 1, 1, 0, 0, 0, 1}, // 4
  {1, 1, 1, 1, 1, 1, 1, 1}, // 5
  {1, 1, 1, 1, 1, 1, 1, 1}, // 6
  {1, 1, 1, 1, 1, 1, 1, 1}, // 7
  {0, 0, 0, 0, 0, 0, 0, 1}, // 8
  {1, 1, 1, 1, 1, 1, 1, 1}, // 9
};

int t = 0;
int digid = 0;
void loop() {
  t += 1;
  if (t > 9999) t = 0;
  if ((t % 1000) == 0) {
    digid = t / 1000; //Каждую секунду отображаем цифры подряд
  }
  for (int i = 0; i < 3; i++) { // Каждый разряд по очереди
    for (int k = 0; k < 8; k++) {// Каждый сегмент по очереди - исходя из заданной карты
      digitalWrite(segmentsPins[k], ((seg[digid][k] == 1) ? HIGH : LOW));
    }
    digitalWrite(anodPins[i], HIGH);
    delay(0); 
    digitalWrite(anodPins[i], LOW); 
    delay(0); 
    digitalWrite(anodPins2[i], HIGH);
    delay(0); 
    digitalWrite(anodPins2[i], LOW); 
  }
}

**Comment by ksv-success** [comment]
Проще конечно новый купить, не пытаться восстановить,  но хочется запустить его но чувствую надолго меня не хватит )) не могу понять в чем причина амперметр индикатор горит только первый индикатор 
![image](https://user-images.githubusercontent.com/59658638/72046797-2abc7d80-32ca-11ea-9c9c-5eaecf26c5db.png)
от STM8 к индикатору все линии анодов без обрывов возможно PCB многослойная? и между слоями КЗ короткое замыкание буду проверять... проверил обрывов и короткого замыкания нет но почему то не хочет работать буду дальше разбираться

**Comment by ksv-success** [comment]
Это в коде что то не так я уверен

**Comment by ksv-success** [comment]
Или брак STM8 дождусь партии других STM8 возможно паравда брак

**Comment by cocus** [comment]
Ok so it's weird that you only have those segments on. However, if those two are off, it means an issue with Anode D3 and D2 from display DS2. Can you verify with an oscilloscope that those pins are pulsing at least?

**Comment by ksv-success** [comment]
Забыл совсем про осциллограф) посмотрю сигнал есть ли пульсации или нет и скажу что да как

**Comment by ksv-success** [comment]
![IMG_20200110_120233](https://user-images.githubusercontent.com/59658638/72140647-3e3b1780-33a2-11ea-9aab-2fc2cd37f3fe.jpg)
это нормально работающие индикаторы.

**Comment by ksv-success** [comment]
![IMG_20200110_115803](https://user-images.githubusercontent.com/59658638/72140648-3ed3ae00-33a2-11ea-8be2-4731a0e53fdd.jpg)
это те которые не работают. видно что пульсации есть но хаотичные похоже на шумы измерял уже на 0.1 v а не на 0.5 v как другие и частота 5kHz в двое выше

**Comment by ksv-success** [comment]
![IMG_20200110_115457](https://user-images.githubusercontent.com/59658638/72140649-3f6c4480-33a2-11ea-8e82-1d28f34f6d1f.jpg)

это один из трех нижних который горит. Что скажете?

**Comment by ksv-success** [comment]
не работает D1 и D3. D2 это 5 вывод STM8 но он работает с искажениями

**Comment by ksv-success** [comment]
мне кажется причина в микроконтроллере и он неисправен либо я что-то не так запрограммировал что не исключено но все же странно что остальные работают

**Comment by ksv-success** [comment]
выпаял впаял обратно странно заработал ещё один индикатор следующий не было ни короткого замыкания ни обрыва но заработал неправильно не показывает некоторые цифры может быть плохой флюс и надо полностью распаивать промывать и спаивать обратно.. 1,0,7 показывает остальные цифры не хочет отображать

**Comment by cocus** [comment]
What does "burns"? should not be anything burning. if it's, then you might have a short somewhere or there might be some differences on the pcb you have vs the one I've used. Let's focus on fixing all the hardware issues first, and then focus on the software.

**Comment by ksv-success** [comment]
хорошо разберусь разберусь с аппаратной частью если что все равно не заработает тогда напишу  опять

**Comment by ksv-success** [comment]
грешу на программатор китайский ST-Link V2 с микроконтроллером CKS32F103C8T6 попробую завтра через arduino uno
 порограммировать

**Comment by ksv-success** [comment]
![IMG_20200111_201909](https://user-images.githubusercontent.com/59658638/72208077-c9ee9a00-34af-11ea-82dd-eee9d4a38a7d.jpg)
Запаял 2 дисплея с общим катодом которые стояли изначально вроде бы все заработало но показывает 11 в амперметре видимо схема немного другая

**Comment by ksv-success** [comment]
Странно но с общим анодом не работало

**Comment by ksv-success** [comment]
Показывает в амперах вольты и на оборот буду смотреть попробую изменить и нужно как-то установить нулевое значение на вольтах

**Comment by ksv-success** [comment]
как откалибровать его и выставить запятую?

**Comment by ksv-success** [comment]
сейчас на стандартном вашем коде ничего не менял у меня показывает вольтметр 077 амперметр 057

**Comment by ksv-success** [comment]
Дорогой
