### ISSUE TITLE
How to calibrate

### ISSUE THREAD

**Issue by ksv-success** [cocus/vc288-alt-fw#6]
Please my friend tell me how to calibrate?, I connected 12 volts for measurement, it shows 319 volts and should show 12

**Comment by ksv-success** [comment]
![IMG_20200112_211925](https://user-images.githubusercontent.com/59658638/72223566-4dc48700-3581-11ea-8e1e-1455d54aca84.jpg)
Такие значения показывает я ничего не менял просто установил ваш код в устройство

**Comment by ksv-success** [comment]
пожалуйста подскажите я все еще не разобрался как выставить 000 вольтметр и 000 амперметр и чтобы показывало 12 вольт а не 300 вольт

**Comment by cocus** [comment]
Hi, the calibration routine was not working to the full extents. And didn't seem to be accurate enough. Right now it calibrates itself each time you turn it on; which means you shouldn't connect any external voltages to it when it powers up. If you still get a wrong indication, then the resistor divider you have might be different than the ones on the schematic. Please have a look at config.h on line 40, where 8200 and 290000 were the values of the resistors (in ohms) used in the voltage divider.

**Comment by ksv-success** [comment]
спасибо огромное вам! буду побывать.  А как выставить нулевые значения? показывает 077 вольт метр и 052 амперметр или это после калибровки само исправится  ?

**Comment by ksv-success** [comment]
да действительно отличаются не много от схемы и 270kOm был заменён на 300 введу свои значения

**Comment by cocus** [comment]
Theoretically the calibration gets rid of said offset. But I can't verify it. I left the development of this right before having it correctly working. You can add your contributions if you find out a better way to calibrate. Thank you

**Comment by ksv-success** [comment]
Спасибо я бы с радостью но я плохой программист,  а ваш проект хороший !

**Comment by ksv-success** [comment]
я изменил (((8200.0f + 301600.0f ) / 10540.0f) * 33.0f / 1024.0f) но ничего не изменилось

**Comment by ksv-success** [comment]
33.0f / 1024.0f) это что значит для чего это?

**Comment by cocus** [comment]
there's an error in your formula. you should change both numbers at the same time, i.e. 8200 in both instances. I'm not sure what's the 10540 value.
33 / 1024 is the scale of the ADC (i.e. 3.3 volts of the Vref and 1024 counts)

**Comment by ksv-success** [comment]
хорошо я понял спасибо то есть значение 33.0 это 3.3 вольт

**Comment by ai-big-boss** [comment]
если я ставлю значение 4  в этой строчке "#define ADC_AVERAGE_SAMPLES_BASE_2      4"
тогда показывает немного верное значение но без запятой

**Comment by ksv-success** [comment]
Все так же отображает теже символы  (((8200.0f + 301600.0f) / 8200.0f) * 33.0f / 1024.0f)

**Comment by ksv-success** [comment]
011 вольтметр 052-051  амперметр

**Comment by ksv-success** [comment]
![image](https://user-images.githubusercontent.com/59658638/72272228-5b3d4800-3639-11ea-8a53-663974487e79.png)

**Comment by cocus** [comment]
ADC_AVERAGE_SAMPLES_BASE_2 is a constant that sets how many samples you want to average. if you change that value, the values might get better. yeah, probably the zero offset calibration might not be working. also, you could tweak the values of lines 99 and 101 from main.c to get better readings. I can't help further than that since I don't have a dev kit set up to continue working on this. probably on the future.

**Comment by ksv-success** [comment]
Спасибо буду пытаться что то сделать надеюсь получится

**Comment by ksv-success** [comment]
получилось настройкой строк 99 и 101 из main.c вышло примерно так        
 fvalue = (float)0.129f;
        fvalue *= get_adc_volts();
        value = fvalue + 0.044f;

**Comment by ksv-success** [comment]
как сделать отображение например сотых вольт 12.1 - 12.9 не подскажите?

**Comment by ksv-success** [comment]
![IMG_20200113_201407](https://user-images.githubusercontent.com/59658638/72276623-6bf1bc00-3641-11ea-99a8-298684678211.jpg)

**Comment by ksv-success** [comment]
Получилось спасибо большое ещё бы запятую после было бы вообще супер вы хороший человек и разработчик великолепный! если мог бы отблагодарить вас как появится возможность отблагодарить вас дайте в описание ваш кошелек если вам это принесет пользу спасибо огромное вам!

**Comment by ksv-success** [comment]
в config заменил 
   #define ADC_AVERAGE_SAMPLES_BASE_2      4
   #define GAIN_FOR_VOLTAGE                (((8200.0f + 312140.0f) / 8200.0f) * 33.0f / 1024.0f)

в main заменил
 fvalue = (float)0.124f;
        fvalue *= get_adc_volts();
        value = fvalue + 0.044f;

        set_display_from_int(value, 0);
        delay(200);

теперь показывает 012 вольт 000 ампер . амперметр не проверял

**Comment by MrDrGEM** [comment]
Привет всем. Столкнулся тоже с проблемой калибровки. Залил актуальную прошивку. Версия платы 1, при подаче питания 5в - показания 11,3
6в  -  21,5 
7в  -  32.8 
8в  -  43,0
Резисторы перепроверил тестером и вроде соответствуют скетчу RV1,2 - 20k , R1-8k2 , R2-270k , R3-180k , R4-8k2
Подскажите правильное направление решения. Спасибо.
**ENG**
Hello everybody. I also ran into a calibration problem. Uploaded the current firmware. Board version 1, when the input power is 5V - display show 11.3
6v  -  21.5
7v  -  32.8
8v  -  43.0
I checked the resistors with a tester and seem to correspond to the sketch RV1,2 - 20k, R1-8k2, R2-270k, R3-180k, R4-8k2
Prompt the right direction of the solution. Thank you.
